nome = input("Digite um funcionario")
empresa = input("Digite a instituição")
qntde_funcionarios = int(input("Digite a quantidade de funcionarios: "))
mediaMensalidade = float(input("Digite a media da mensalidade: "))
print(nome + "trabalha na empresa " + empresa)
print("Possui:", qntde_funcionarios, " funcionarios.")
print("====================Verifique os tipos de dados==================")
print("O tipo de dado da variavel [nome] é: ", type(nome))
print("O tipo de dado da variavel [empresa] é: ", type(empresa))
print("O tipo de dado da variavel [qntde_funcionarios] é: ", type(qntde_funcionarios))
print("O tipo de dado da variavel [mediaMensalidade] é: ", type(mediaMensalidade))